AllCops:
  EnabledByDefault: true

Layout/EndOfLine:
  Enabled: false

Layout/IndentationWidth:
  Width: 2

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: false

Lint/ConstantResolution:
  Enabled: false

Layout/FirstMethodArgumentLineBreak:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/Copyright:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false